export const endpoints = {
  auth: {
    login: '/auth/login',
    register: '/auth/register',
    google: '/auth/google',
    me: '/auth/me',
    logout: '/auth/logout',
    refresh: '/auth/refresh',
  },
  novels: {
    list: '/novels',
    detail: (novelId: string) => `/novels/${novelId}`,
    create: '/novels',
    update: (novelId: string) => `/novels/${novelId}`,
    delete: (novelId: string) => `/novels/${novelId}`,
    view: (novelId: string) => `/novels/${novelId}/view`,
    viewEvent: (novelId: string) => `/novels/${novelId}/view-event`,
    myInteraction: (novelId: string) => `/novels/${novelId}/me`,
    toggleFollow: (novelId: string) => `/novels/${novelId}/follow/toggle`,
    toggleLike: (novelId: string) => `/novels/${novelId}/like/toggle`,
    toggleBookmark: (novelId: string) => `/novels/${novelId}/bookmark/toggle`,
    latest: '/novels/latest-updates',
    completed: '/novels/completed',
    coverSignature: (novelId: string) => `/novels/${novelId}/cover/upload-signature`,
    cover: (novelId: string) => `/novels/${novelId}/cover`,
  },
  search: {
    novels: '/search/novels',
    suggestions: '/search/suggestions',
  },
  advancedSearch: {
    novels: '/advanced/search/novels',
    semanticNovels: '/advanced/search/semantic/novels',
    reindexNovels: '/advanced/search/reindex/novels',
    rebuildNovels: '/advanced/search/reindex/novels/rebuild',
    diagnostics: '/advanced/search/diagnostics',
  },
  chatbot: {
    message: '/chatbot/message',
  },
  recommendations: {
    similarNovels: (novelId: string) => `/recommendations/novels/${novelId}/similar`,
    semanticSimilarNovels: (novelId: string) => `/recommendations/novels/${novelId}/similar/semantic`,
    hybridSimilarNovels: (novelId: string) => `/recommendations/novels/${novelId}/similar/hybrid`,
    forYou: '/recommendations/for-you',
  },
  lastReads: {
    list: '/last-reads',
    updateNovelChapter: (novelId: string, chapterId: string) => `/last-reads/novels/${novelId}/chapters/${chapterId}`,
  },
  bookmarks: {
    list: '/bookmarks',
    novels: '/bookmarks/novels',
    chapters: '/bookmarks/chapters',
    novelExists: (novelId: string) => `/bookmarks/novels/${novelId}/exists`,
    chapterExists: (chapterId: string) => `/bookmarks/chapters/${chapterId}/exists`,
    createNovel: (novelId: string) => `/bookmarks/novels/${novelId}`,
    createChapter: (chapterId: string) => `/bookmarks/chapters/${chapterId}`,
    deleteNovel: (novelId: string) => `/bookmarks/novels/${novelId}`,
    deleteChapter: (chapterId: string) => `/bookmarks/chapters/${chapterId}`,
  },
  follows: {
    novels: '/follows/novels',
  },
  users: {
    detail: (userId: string) => `/users/${userId}`,
    avatarSignature: '/users/me/avatar/upload-signature',
    avatar: '/users/me/avatar',
  },
  genres: {
    list: '/genres',
  },
  tags: {
    list: '/tags',
    byNovel: (novelId: string) => `/tags/novels/${novelId}`,
  },
  chapters: {
    byNovel: (novelId: string) => `/novels/${novelId}/chapters`,
    detail: (chapterId: string) => `/chapters/${chapterId}`,
    update: (chapterId: string) => `/chapters/${chapterId}`,
    delete: (chapterId: string) => `/chapters/${chapterId}`,
  },
  rankings: {
    list: '/rankings',
    ranking: (metric: string, period: string) => `/novel-rankings/${metric}/${period}`,
    total: (metric: string, period: string) => `/novel-rankings/${metric}/total/${period}`,
  },
  adminUsers: {
    list: '/admin/users',
    detail: (userId: string) => `/admin/users/${userId}`,
    create: '/admin/users',
    update: (userId: string) => `/admin/users/${userId}`,
    delete: (userId: string) => `/admin/users/${userId}`,
  },
  adminChatbot: {
    summary: '/admin/chatbot/summary',
    reload: '/admin/chatbot/reload',
    importDefaults: '/admin/chatbot/import-defaults',
    reindexEmbeddings: '/admin/chatbot/embeddings/reindex',
    embeddingStatus: '/admin/chatbot/embeddings/status',
    faqs: '/admin/chatbot/faqs',
    faq: (id: string) => `/admin/chatbot/faqs/${encodeURIComponent(id)}`,
    intents: '/admin/chatbot/intents',
    intent: (id: string) => `/admin/chatbot/intents/${encodeURIComponent(id)}`,
  },
  comments: {
    byNovel: (novelId: string) => `/novels/${novelId}/comments`,
    byChapter: (chapterId: string) => `/chapters/${chapterId}/comments`,
    replies: (commentId: string) => `/comments/${commentId}/replies`,
    context: (commentId: string) => `/comments/${commentId}/context`,
    detail: (commentId: string) => `/comments/${commentId}`,
    moderationDelete: (commentId: string) => `/comments/${commentId}/moderation`,
  },
  notifications: {
    list: '/notifications',
    unread: '/notifications/unread',
    unreadCount: '/notifications/unread/count',
    markRead: (notificationId: string) => `/notifications/${notificationId}/read`,
    markAllRead: '/notifications/read-all',
    delete: (notificationId: string) => `/notifications/${notificationId}`,
    deleteAll: '/notifications',
    sendToUser: (userId: string) => `/notifications/users/${userId}`,
    sse: '/notifications/stream',
  },
  crawlTasks: {
    list: '/crawl-tasks',
    create: '/crawl-tasks',
    detail: (taskId: string) => `/crawl-tasks/${taskId}`,
    chapterRecords: '/crawl-tasks/crawl-chapter-records',
    chapterRecord: (recordId: string) => `/crawl-tasks/crawl-chapter-records/${recordId}`,
  },
  dataReports: {
    userEvents: '/data-reports/user-events',
    rebuildInteractions: '/data-reports/user-novel-interactions/rebuild',
    userNovelInteractions: '/data-reports/user-novel-interactions',
  },
} as const;
