export const queryKeys = {
  auth: ['auth'] as const,
  novels: ['novels'] as const,
  genres: ['genres'] as const,
  tags: ['tags'] as const,
  chapters: ['chapters'] as const,
  audio: ['audio'] as const,
  rankings: ['rankings'] as const,
  notifications: ['notifications'] as const,
  crawlTasks: ['crawlTasks'] as const,
  search: ['search'] as const,
  collection: ['collection'] as const,
  adminUsers: ['adminUsers'] as const,
  adminChatbot: ['adminChatbot'] as const,
  adminAudio: ['adminAudio'] as const,
  users: ['users'] as const,
  comments: ['comments'] as const,
  dataReports: ['dataReports'] as const,
  recommendations: ['recommendations'] as const,
} as const;
