export const queryKeys = {
  auth: ['auth'] as const,
  novels: ['novels'] as const,
  genres: ['genres'] as const,
  tags: ['tags'] as const,
  chapters: ['chapters'] as const,
  rankings: ['rankings'] as const,
  notifications: ['notifications'] as const,
  crawlTasks: ['crawlTasks'] as const,
  search: ['search'] as const,
  collection: ['collection'] as const,
  adminUsers: ['adminUsers'] as const,
  users: ['users'] as const,
  comments: ['comments'] as const,
} as const;
